os: linux
language: node_js
node_js:
  - stable
dist: xenial

cache:
  directories:
  - node_modules

before_script: cd server

script:
  - npm install
  - npm install coverage coveralls nyc
  - npm run test

after_success:
 - nyc report --reporter=text-lcov | coveralls && nyc report --reporter=lcov
 - cat ./coverage/lcov.info | coveralls

notifications:
  slack:
    rooms:
      - sytwull:NkXaHBTkYgaYfp5mhS6MDbuu#e10