os: linux
language: node_js
node_js:
  - stable
dist: xenial

cache:
  directories:
  - node_modules

before_script: cd server

script:
  - npm install
  - cd ../client 
  - npm install && npm run test:unit
  - cd ../
  - npm install coveralls nyc
  - nyc npm test --prefix server
  - nyc report --reporter=lcov
  - cat ./coverage/lcov.info | coveralls

notifications:
  slack:
    rooms:
      - sytwull:NkXaHBTkYgaYfp5mhS6MDbuu#e10